version: '3'

services: 

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend: 
    container_name: backend
    build: ./refreps-back-end
    ports:
      - '3000:3000'
    environment: 
      - HOST=localhost
      - PORT=3000
      - DB_CONNECT=mongodb://mongo:27017/refrep
      - TOKEN_SECRET=random_string
      - LOCAL_UPLOAD_PATH=uploads/
      - FRONTEND_URL=http://localhost:4200
      - SEND_EMAILS=false
      - GOOGLE_USER=email
      - GOOGLE_OAUTH_CLIENT_ID=id
      - GOOGLE_OAUTH_CLIENT_SECRET=secret
      - GOOGLE_OAUTH_REFRESH_TOKEN=secret
    links:
      - mongo

  frontend:
    container_name: frontend
    build: ./refprep-frontend
    ports:
      - "80:80"



